#.travis.yml

dist: trusty
sudo: false

language: node_js
node_js:
  - "6.9"


cache:
  directories:
     - ./node_modules

branches:
  only:
    - master
    - dev

before_script:
  # - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install @angular/material@2.0.0-beta.10
  - npm install @angular/cdk@2.0.0-beta.10

script:
  - ng build --prod
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js

after_success:
  # - firebase deploy --token $FIREBASE_TOKEN

notifications:
  slack: cen5035-uf:Yd5Sd6HvnpVAbLsbm9qRIJkn
